name: 'Strapi Deployment'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    needs: terraform
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy Strapi Application
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        instance_ip=$(terraform output -raw instance_ip)
        ssh -o StrictHostKeyChecking=no -i /home/ubuntu/TASK2.pem ubuntu@$instance_ip "rm -rf /srv/strapi/*"
        scp -o StrictHostKeyChecking=no -i /home/ubuntu/TASK2.pem -r . ubuntu@$instance_ip:/srv/strapi
        ssh -o StrictHostKeyChecking=no -i /home/ubuntu/TASK2.pem ubuntu@$instance_ip "cd /srv/strapi && yarn install && pm2 restart strapi"
