name: Strapi Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Deploy Strapi Application
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.PRIVATE_KEY }} ubuntu@${{ secrets.EC2_PUBLIC_IP }} "sudo rm -rf /srv/strapi/*"
          scp -o StrictHostKeyChecking=no -i ${{ secrets.PRIVATE_KEY }} -r * ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/srv/strapi
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.PRIVATE_KEY }} ubuntu@${{ secrets.EC2_PUBLIC_IP }} "cd /srv/strapi && yarn install && pm2 restart strapi"
