name: CI/CD for Strapi

on:
  push:
    branches:
      - madhu  # Trigger on pushes to main branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0  # Adjust to the version you are using

      - name: Initialize Terraform
        run: terraform init

      - name: Plan Terraform changes
        run: terraform plan

      - name: Apply Terraform changes
        id: apply
        run: terraform apply -auto-approve

      - name: Output Terraform Outputs
        run: |
          echo "Instance Public IP: ${{ steps.apply.outputs.instance_public_ip }}"
          echo "Instance Private IP: ${{ steps.apply.outputs.instance_private_ip }}"
        id: terraform_output
        env:
          INSTANCE_PUBLIC_IP: ${{ steps.apply.outputs.instance_public_ip }}
          INSTANCE_PRIVATE_IP: ${{ steps.apply.outputs.instance_private_ip }}

  deploy:
    runs-on: ubuntu-latest
    needs: terraform  # Ensure the Terraform job completes successfully before deployment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.INSTANCE_PUBLIC_IP }}  # Use the public IP obtained from Terraform
          username: ${{ secrets.EC2_USERNAME }}  # SSH username for the EC2 instance
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # SSH private key for authentication
          script: |
            cd /srv/strapi  # Assuming Strapi is deployed under /srv/strapi on the EC2 instance
            git pull origin main  # Pull the latest code from your repository
            yarn install  # Install dependencies if needed
            pm2 restart strapi  # Restart Strapi using PM2 (assuming it's managed by PM2)

            # Optionally, you can add more commands here for your deployment process
